### ISSUE TITLE
Add meta information to each page

### ISSUE THREAD

**Issue by OliverDudgeon** [InformaticsMatters/mini-apps-data-tier-ui#16]
We should

- [ ] Set titles on each main page using next/head Head component
- [ ] Page descriptions via Head
- [ ] Fix the favicon not loading from the root site
- [ ] Other similar SEO optimisations to be added

**Comment by OliverDudgeon** [comment]
Note that after switching to `xdm`, the `next/head` `Head` component is required in `mdx` files

**Comment by OliverDudgeon** [comment]
The main squonk site has been updated which the dm-ui sources it's icon from
